apiVersion: apps/v1
kind: Deployment
metadata:
  name: catsdogs-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catsdogs
  template:
    metadata:
      labels:
        app: catsdogs
    spec:
      containers:
      - name: catsdogs
        image: catsdogs:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: catsdogs-svc
spec:
  selector:
    app: catsdogs
  ports:
  - port: 80
    targetPort: 8000
  type: NodePort
