apiVersion: apps/v1
kind: Deployment
metadata:
  name: catsdogs-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catsdogs
  template:
    metadata:
      labels:
        app: catsdogs
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: catsdogs
        image: cats-dogs-mlops:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: catsdogs-svc
spec:
  selector:
    app: catsdogs
  ports:
  - port: 80
    targetPort: 8000
  type: NodePort
